name: Multi-media-video-summarization
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
      - absl-py==1.4.0
      - appdirs==1.4.4
      - brotlipy==0.7.0
      - cached-property==1.5.2
      - certifi==2020.12.5
      - cffi==1.14.6
      - chardet==5.0.0
      - charset-normalizer==2.0.12
      - click==8.0.4
      - colorama==0.4.5
      - cryptography==35.0.0
      - cycler==0.11.0
      - dataclasses==0.8
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - gitdb==4.0.9
      - GitPython==3.1.18
      - h5py==3.1.0
      - idna==2.10
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.3
      - importlib-metadata==4.8.3
      - importlib-resources==5.4.0
      - joblib==1.1.1
      - kiwisolver==1.3.1
      - matplotlib==3.3.4
      - mkl-fft==1.3.0
      - mkl-random==1.1.1
      - mkl-service==2.3.0
      - moviepy==1.0.3
      - numpy==1.19.5
      - olefile==0.46
      - opencv-python==4.5.1.48
      - ortools==8.2.8710
      - pandas==1.1.5
      - pathtools==0.1.2
      - Pillow==8.4.0
      - pip==21.2.2
      - proglog==0.1.9
      - promise==2.3
      - protobuf==3.15.6
      - psutil==7.0.0
      - pycparser==2.21
      - pyOpenSSL==22.0.0
      - pyparsing==3.0.4
      - PySocks==1.7.1
      - python-dateutil==2.8.1
      - pytz==2021.1
      - PyYAML==6.0.1
      - requests==2.27.1
      - scikit-learn==0.24.2
      - scipy==1.5.4
      - sentry-sdk==2.29.1
      - setproctitle==1.2.3
      - setuptools==58.0.4
      - shortuuid==1.0.13
      - six==1.16.0
      - sklearn==0.0
      - smmap==5.0.0
      - threadpoolctl==3.1.0
      - tkVideo==0.1
      - torch==1.8.0
      - torchvision==0.9.0
      - tornado==6.1
      - tqdm==4.64.1
      - typing_extensions==4.1.1
      - urllib3==1.26.20
      - wandb==0.12.21
      - wheel==0.37.1
      - win-inet-pton==1.1.0
      - wincertstore==0.2
      - zipp==3.6.0
